### PR TITLE
Updated deps to ensure that fsevents was healthy and to remove vulnerabilities 

### PR DESCRIPTION
**Pull request by rkesters**
- Updated `browser-sync` and `gulp` to remove dep on bad version of fsevents
-  Update jquery to remove vulnerability 
- Update all other dev deps to user latest to make use of latest features

@kball @gakimball please review.

### CODE REVIEW

**Comment by rkesters** [comment]
@DanielRuf could you please review.

**Comment by rkesters** [comment]
@kball @gakimball please review

**Comment by rkesters** [comment]
@DanielRuf

**Comment by DanielRuf** [comment]
@rkesters thanks for your PR. Please do not spam and be patient. We do this in our available free time.

**Comment by DanielRuf** [comment]
The changes are not really relevant as the `^` SemVer selector automatically picks the latest minor release. So for `^4.0.2` it would be `4.3.5` if there is some 4.x release, for example 4.3.5. But would not pick up 5.x.y.

The lockfile is not really relevant for normal installations and only for local development, if `npm ci` or a setup from the lockfile is done at all.

We will update it in one of the next updates.

**Pull request closed without merging**
